Numpy. ДЗ 1: Поиск аргумента максимума
Легкая

Вам дается массив arr произвольной размерности x*y (то есть x столбцов, y строк).

Необходимо вернуть массив Numpy, который содержит индексы макисмальных элементов в каждой строке.

Задание
Напишите функцию FindArgMax, которая будет возвращать массив, состоящий из индексов максимальных элементов в каждой строке.

Функция FindArgMax принимает на вход массив arr.

Функция должна возвращать массив с индексами.

In [5]:
import numpy as np

In [6]:
class Answer:
    def FindArgMax(self, arr):
        res = np.argmax(arr, axis=1)

        return res


arr = np.array([[100, 2, 3, 4], [1, 2, 3, 4], [1, 200, 3, 4]])
print(Answer().FindArgMax(arr))
# Ответ: [0 3 1]

[0 3 1]


Numpy. ДЗ 2: Создание интервала и расширение размерности
Нормальная

Вам заданы три числа:

start
stop
step
Значения всех трех чисел вам заранее неизвестны.

Для начала, необходимо составить последовательность равномерно распределенных чисел в диапазоне start:stop с шагом step. Последовательность должна быть представлена массивом Numpy.

Далее, вы собираетесь подавать эту последовательность на вход нейронной сети. Основное требование сети: входной массив данных должен иметь размерность (observations, size), где:

observations - количество наблюдений (в нашем случае 1, т.к. мы сгенерировали всего 1 последовательность)
size - количество чисел в сгенерированной последовательности
Трансформируйте полученную последовательность таким образом, чтобы она имело нужную размерность.

Важно: Не используйте функцию reshape - воспользуйтесь другими методами Numpy.

Задание
Напишите функцию AddDim, которая будет возвращать сгенерированную последовательность с добавленным единичным измерением.

Функция AddDim принимает на вход числа start, stop, step.

Функция должна возвращать результирующий массив.

In [266]:
import numpy as np


class Answer:
    def AddDim(self, start, stop, step):
        k = 1 if start <= stop else -1

        res1 = np.arange(start, stop, step * k)

        res = np.expand_dims(res1, axis=0)

        return res  # , res.shape


start, stop, step = 1, 10, 2
print(Answer().AddDim(start, stop, step))
# Ответ:    [[1 3 5 7 9]]
start, stop, step = 10, 1, 2
print(Answer().AddDim(start, stop, step))
start, stop, step = -10, -1, 2
print(Answer().AddDim(start, stop, step))
start, stop, step = -1, -10, 2
print(Answer().AddDim(start, stop, step))
start, stop, step = -10, 10, 2
print(Answer().AddDim(start, stop, step))
start, stop, step = 10, -10, 2
print(Answer().AddDim(start, stop, step))

[[1 3 5 7 9]]
[[10  8  6  4  2]]
[[-10  -8  -6  -4  -2]]
[[-1 -3 -5 -7 -9]]
[[-10  -8  -6  -4  -2   0   2   4   6   8]]
[[10  8  6  4  2  0 -2 -4 -6 -8]]


Numpy. ДЗ 1: Контроль температуры
Легкая

У вас есть данные о температуре в разных городах.

Напишите функцию filter_cities_by_temperature, которая принимает на вход два списка одинаковой длины: temperatures и cities и значение threshold_temp.

Функция должна вернуть список городов, в которых температура превышает определенное значение (threshold_temp).

In [267]:
import numpy as np


def filter_cities_by_temperature(temperatures, cities, threshold_temp):
    temperatures = np.array(temperatures)
    cities = np.array(cities)
    # Find indices of cities exceeding the threshold
    valid_indices = np.where(temperatures > threshold_temp)
    # print(valid_indices)

    # Filter city names based on the valid indices
    res = cities[valid_indices]

    return res


temperatures = [25.2, 28.5, 30.1, 23.8, 27.0, 29.5, 31.2]
cities = ["Город А", "Город Б", "Город В", "Город Г", "Город Д", "Город Е", "Город Ж"]
print(filter_cities_by_temperature(temperatures, cities, 28.0))
# ['Город Б', 'Город В', 'Город Е', 'Город Ж']

['Город Б' 'Город В' 'Город Е' 'Город Ж']


In [268]:
def filter_cities_by_temperature(temperatures, cities, threshold_temp):
    zipped = list(zip(cities, temperatures))
    return [city for city, temp in zipped if temp > threshold_temp]


temperatures = [25.2, 28.5, 30.1, 23.8, 27.0, 29.5, 31.2]
cities = ["Город А", "Город Б", "Город В", "Город Г", "Город Д", "Город Е", "Город Ж"]
print(filter_cities_by_temperature(temperatures, cities, 28.0))
# ['Город Б', 'Город В', 'Город Е', 'Город Ж']

['Город Б', 'Город В', 'Город Е', 'Город Ж']


Numpy. ДЗ 2: Конкатенация и очистка массивов
Нормальная

Вам на вход подаются 2 матрицы Numpy A и B произвольного размера.

Заранее вам не известно, но матрицы могут быть «грязными» - там могут присутствовать лишние размерности.

Например:

Исходная размерность: (1, 2, 1, 2, 2)
Должна быть: (2, 2, 2)
Соответственно, первая задача - очистить матрицы от единичных размерностей.

Далее необходимо объединить матрицы «вертикально».

Примечание: Допустим, что нам заранее известно, что размерности очищенных матриц допускают такое объединение.

Задание
Напишите функцию CombineMatrix, которая будет возвращать объединенные матрицы после очистки.

Функция CombineMatrix принимает на вход матрицы A, B.

Функция должна возвращать результирующий массив.

In [269]:
import numpy as np


def CombineMatrix(A: np.ndarray, B: np.ndarray):
    A, B = A.squeeze(), B.squeeze()
    res = np.concatenate((A, B), axis=0)
    return res


# A = np.array([[ 1  2  3  4  5]
#  [ 6  7  8  9 10]])
A = np.arange(1, 11).reshape(2, -1)
# B = [[ 1  3  5  7  9]
#  [ 2  4  6  8 10]]
odd_numbers = np.arange(1, 10, 2)
even_numbers = np.arange(2, 11, 2)
B = np.vstack((odd_numbers, even_numbers))
print(CombineMatrix(A, B))
# Результат
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [ 1  3  5  7  9]
#  [ 2  4  6  8 10]]

A = np.array([1, 2, 1, 2, 2])
B = np.array([2, 2, 2])
print(CombineMatrix(A, B))
# [[[1 2]
#   [1 2]]
#  [[1 2]
#   [1 2]]
#  [[1 2]
#   [1 2]]
#  [[1 2]
#   [1 2]]]

A = np.array([1, 2, 1, 2, 2])
B = np.array([2, 1, 1, 2, 2])
print(CombineMatrix(A, B))
# [[[1 2]
#   [1 2]]
#  [[1 2]
#   [1 2]]
#  [[1 2]
#   [1 2]]
#  [[1 2]
#   [1 2]]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  3  5  7  9]
 [ 2  4  6  8 10]]
[1 2 1 2 2 2 2 2]
[1 2 1 2 2 2 1 1 2 2]


Numpy. ДЗ 1: Кумулятивная сумма
Легкая

Вам дается массив arr произвольной размерности x*y (то есть x столбцов, y строк).

Необходимо вернуть массив Numpy той же формы, но в котором вместо исходных значений содержится рассчитанный накопительный итог по каждому столбцу.

Задание
Напишите функцию CalcCumSum, которая будет возвращать рассчитанный нарастающий итог по каждому столбцу.

Функция CalcCumSum принимает на вход массив arr.

Функция должна возвращать результирующий массив.

In [270]:
class Answer:
    def CalcCumSum(self, arr):
        res = np.cumsum(arr, axis=0)
        return res


arr = np.array([[100, 2, 3, 4], [1, 2, 3, 4], [1, 200, 3, 4]])
print(Answer().CalcCumSum(arr))
# Ответ:
# [[100   2   3   4]
#  [101   4   6   8]
#  [102 204   9  12]]

[[100   2   3   4]
 [101   4   6   8]
 [102 204   9  12]]


Numpy. ДЗ 2: Среднее значение и медиана
Легкая

У вас есть массив данных hours_of_sleep, содержащий информацию о продолжительности сна разных людей в часах.

Напишите функцию calculate_mean_and_median, которая принимает массив и возвращает два значения: среднее и медиану этого массива.

In [271]:
import numpy as np


def calculate_mean_and_median(arr):
    return np.average(arr), np.median(arr)


hours_of_sleep = np.array([7, 6, 8, 7, 9, 5, 6, 7, 8, 7])
print(calculate_mean_and_median(hours_of_sleep))
# (7.0, 7.0)

(7.0, 7.0)


Numpy. ДЗ 2: Дисперсия и стандартное отклонение
Легкая

У вас есть массив данных sales_per_week, содержащий информацию о количестве проданных товаров за неделю в разных магазинах.

Напишите функцию calculate_variance_and_stddev, которая принимает этот массив и возвращает дисперсию и стандартное отклонение, округленные до 2 знаков после запятой.

In [272]:
import numpy as np


def calculate_variance_and_stddev(arr):
    return round(np.var(arr), 2), round(np.std(arr), 2)


sales_per_week = np.array([100, 120, 90, 110, 80, 130, 100, 90, 95, 115])
print(calculate_variance_and_stddev(sales_per_week))
# (216.0, 14.7)

(216.0, 14.7)


Numpy. ДЗ 1: Статистическая обработка массива
Легкая

Вам дается массив arr произвольной размерности. Также задан параметр type, который указывает, как производить статистическую обработку:

colwise - по столбцам
rowwise - по строкам
Необходимо рассчитать основные статистические характеристики с учетом параметра type.

Задание
Напишите функцию CalsStatistics, которая будет рассчитывать основные статистические характеристики:

среднее значение
дисперсию
стандартное отклонение
сумму
Если параметр type равен colwise, то расчет нужно производить по столбцам.
Если параметр type равен rowwise, то расчет нужно производить по строкам.

Функция CalsStatistics принимает на вход:

arr - произвольный массив Numpy
type - тип расчета (по строкам или по столбцам)
Функция должна возвращать рассчитанные характеристики:

среднее значение
дисперсию
стандартное отклонение
сумму

In [273]:
import numpy as np


class Answer:
    def CalsStatistics(self, arr, type):
        k = 0 if type == "colwise" else 1

        return (
            np.mean(arr, axis=(k)),
            np.var(arr, axis=(k)),
            np.std(arr, axis=(k)),
            np.sum(arr, axis=(k)),
        )


# Пример для суммы:
arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
type = "colwise"
print(Answer().CalsStatistics(arr, type))
# Ответ: [ 3  6  9 12]

# Пример для суммы:
arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
type = "rowwise"
# Ответ: [10 10 10]

# Пример:
arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
type = "rowwise"
print(Answer().CalsStatistics(arr, type))
# Ответ:
# среднее: array([2.5, 2.5, 2.5])
# дисперсия: array([1.25, 1.25, 1.25])
# ст. отклонение: array([1.11803399, 1.11803399, 1.11803399])
# сумма: array([10, 10, 10])

(array([1.00, 2.00, 3.00, 4.00]), array([0.00, 0.00, 0.00, 0.00]), array([0.00, 0.00, 0.00, 0.00]), array([ 3,  6,  9, 12]))
(array([2.50, 2.50, 2.50]), array([1.25, 1.25, 1.25]), array([1.12, 1.12, 1.12]), array([10, 10, 10]))


Numpy. ДЗ 2: Множественные преобразования матриц
Нормальная

Вам даны 2 матрицы произвольного размера - A и B. Форма и размер матриц вам заранее неизвестны.

Прежде чем делать какие-то совместные операции над этими матрицами, вам нужно их подготовить. А именно, привести к форме, которая позволит эти операции делать:

Матрица A должна иметь размерность Z*2 (где Z количество строк, а 2 - столбцов)
Матрица B должна иметь размерность 2*Y (где 2 количество строк, а Y - столбцов)
Примечание: Числа Z и Y вам неизвестны - они зависят от исходной размерности матриц A и B. Однако, вы точно знаете, что из A и B можно сделать матрицы указанной размерности, правильно подобрав числа Z и Y.

Примечание: Если число столбцов в первой матрице равно числу строк во второй, то такое умножение допустимо. Именно для этого мы и производим обработку в предыдущем пункте.

После этого вы должны выполнить следующие совместные преобразования:

Создайте единичную матрицу той же размерности, что и B
Почленно сложите результат п.1 и B
Умножьте матрицу A на результат п. 2 (матрично)
Транспонируйте полученную в п. 3 матрицу
Умножьте каждый член матрицы из п. 4 на 100

Задание
Напишите функцию TransformMatrix, которая будет возвращать результат всех преобразований, описанных выше.
Функция TransformMatrix принимает на вход матрицы A и B, представленные в виде массивов Numpy.
Функция должна возвращать результирующий массив.

In [274]:
import numpy as np


class Answer:
    def TransformMatrix(self, A, B):
        # v2
        A = A.reshape(-1, 2)
        B = B.reshape(2, -1)
        C = np.ones_like(B)
        return np.dot(A, (C + B)).T * 100

        # v1
        # print(A, A.shape)
        # print(B, B.shape)
        A = A.reshape(-1, 2)
        B = B.reshape(2, -1)
        # print(A, A.shape)
        # print(B, B.shape)
        C = np.ones_like(B)
        # print(C, C.shape)
        p2_sum = C + B
        # print(p2_sum)
        p3 = np.dot(A, p2_sum)
        # print(p3)
        p4 = p3.T
        # print(p4)
        p5 = p4 * 100
        print(p5)


A = np.array([[1, 2, 3, 4], [4, 3, 2, 1], [5, 6, 7, 8], [9, 9, 9, 9]])
B = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]])
print(Answer().TransformMatrix(A, B))
# Ответ:
# [[ 600 1400 1400  600 2200 3000 3600 3600]
#  [ 900 2100 2100  900 3300 4500 5400 5400]
#  [1200 2800 2800 1200 4400 6000 7200 7200]
#  [ 600 1400 1400  600 2200 3000 3600 3600]
#  [ 900 2100 2100  900 3300 4500 5400 5400]
#  [1200 2800 2800 1200 4400 6000 7200 7200]]

[[ 600 1400 1400  600 2200 3000 3600 3600]
 [ 900 2100 2100  900 3300 4500 5400 5400]
 [1200 2800 2800 1200 4400 6000 7200 7200]
 [ 600 1400 1400  600 2200 3000 3600 3600]
 [ 900 2100 2100  900 3300 4500 5400 5400]
 [1200 2800 2800 1200 4400 6000 7200 7200]]


Numpy. ДЗ 2: Умножение матриц с весами
Нормальная

Дана матрица A размером 4x3 и вектор v размером 3. Кроме того, дан вектор весов w размером 4.

Необходимо написать функцию weighted_matrix_vector_multiplication, которая вычисляет взвешенную сумму произведения матрицы A на вектор v, где каждый элемент произведения умножается на соответствующий элемент вектора весов w.

In [275]:
def weighted_matrix_vector_multiplication(A, v, w):
    # print(A.shape, v.shape, w.shape)
    one = np.inner(A, v)
    # print(one, one.shape)
    res = np.outer(w, one)
    return res


A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

v = np.array([2, 3, 4])
w = np.array([0.5, 1, 1.5, 2])
weighted_matrix_vector_multiplication(A, v, w)
# array([[ 10. ,  23.5,  37. ,  50.5],
#        [ 20. ,  47. ,  74. , 101. ],
#        [ 30. ,  70.5, 111. , 151.5],
#        [ 40. ,  94. , 148. , 202. ]])

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([0, 1, -1])
w = np.array([1, 0.5, 2, 1.5])
weighted_matrix_vector_multiplication(A, v, w)

array([[-1.00, -1.00, -1.00, -1.00],
       [-0.50, -0.50, -0.50, -0.50],
       [-2.00, -2.00, -2.00, -2.00],
       [-1.50, -1.50, -1.50, -1.50]])

Numpy. ДЗ 2: Решение СЛУ
Нормальная

Напишите функцию solve_linear_equations, которая принимает матрицу коэффициентов A и вектор правой части b в качестве входных данных и находит решение этой системы уравнений.

Пример

# Допустим есть следующая СЛУ
2x + 3y + z = 10
 x +  y + z =  6
3x + 2y + 2z = 12

# Матрица коэффициентов будет выглядеть следующим образом:
A = np.array([[2, 3, 1],
              [1, 1, 1],
              [3, 2, 2]])

# Вектор правой части:
b = np.array([10, 6, 12])

solve_linear_equations(A, b)
# [1.48029737e-16 2.00000000e+00 4.00000000e+00]

In [276]:
def solve_linear_equations(A, b):
    return np.linalg.solve(A, b)


A = np.array([[2, 3, 1], [1, 1, 1], [3, 2, 2]])
b = np.array([10, 6, 12])
xyz = solve_linear_equations(A, b)
xyz

array([0.00, 2.00, 4.00])

2x + 3y + z = ?
 x +  y + z =  ?
3x + 2y + 2z = ?
x,y,z = 1.48029737e-16, 2.00000000e+00, 4.00000000e+00

A = np.array([[2, 3, 1], [1, 1, 1], [3, 2, 2]])
xyz = np.array([1.48029737e-16, 2.00000000e+00, 4.00000000e+00])

In [277]:
def solve_linear_equations(A, xyz):
    return np.dot(A, xyz)


solve_linear_equations(A, xyz)

array([10.00, 6.00, 12.00])

Numpy. ДЗ 2: Индексация и замена значений
Нормальная

Дан двумерный массив целых чисел array.

Напишите функцию replace_values_with_logic, которая принимает этот массив и заменяет отрицательные значения в массиве на нули, а положительные значения на их квадраты.

In [278]:
import numpy as np


class Answer:
    def replace_values_with_logic(self, arr):
        # v1
        # return [[0 if n < 0 else n**2 for n in subarr] for subarr in arr]

        # v2
        return np.where(arr < 0, 0, arr**2)

        # v3
        positive_mask = array > 0
        negative_mask = array < 0

        array[positive_mask] = np.square(array[positive_mask])
        array[negative_mask] = 0


array = np.array([[2, -3, 4], [-1, 5, -6], [7, 8, -9]])
print(Answer().replace_values_with_logic(array))

[[ 4  0 16]
 [ 0 25  0]
 [49 64  0]]


Numpy. ДЗ 2: Копирование массива и поиск элементов по условиям
Нормальная

Вам на вход подается матрица A произвольного размера.

Для начала, необходимо создать матрицу B, которая является копией матрицы A.

Примечание: При этом при изменении матрицы A, матрица B должна остаться неизменной.

После этого необходимо транспонировать матрицу A.

В конце необходимо найти и отобрать только те элементы матрицы A, которые больше 7 или меньше 2, вне зависимости от размерности.

Задание
Напишите функцию CopyAndSelect, которая будет возвращать:

матрицу B
матрицу A
массив отобранных значений
Функция CopyAndSelect принимает на вход матрицу A.

In [279]:
import numpy as np


class Answer:
    def CopyAndSelect(self, arr):
        A = arr
        B = A.copy()
        A = A.T
        # v1
        # mask = (A > 7) | (A < 2)
        # return A[mask], A, B

        # v2
        result = np.where((A > 7) | (A < 2), A, np.nan)
        return result[~np.isnan(result)].tolist()


array = np.array([[2, -3, 4], [-1, 5, -6], [7, 8, -9]])
print(Answer().CopyAndSelect(array))

[-1.0, -3.0, 8.0, -6.0, -9.0]


Numpy. ДЗ 2: Логическое объединение массивов
Нормальная

Даны два одномерных массива булевых значений одинаковой длины.

Напишите функцию logical_or_arrays, которая принимает два массива и создает новый массив, содержащий элементы, которые являются результатом логического ИЛИ для соответствующих элементов исходных массивов.

In [280]:
import numpy as np


def logical_or_arrays(arr1: bool, arr2: bool):
    # v1 classic lc
    # zipped = zip(arr1, arr2)
    # return [x or y for x, y in zipped]

    # v2
    return arr1 | arr2


array1 = np.array([True, False, True, False, True])
array2 = np.array([False, True, True, False, False])

print(logical_or_arrays(array1, array2))
# array([ True,  True,  True, False,  True])

[ True  True  True False  True]


Numpy. ДЗ 2: Случайные числа и плоские массивы
Нормальная

Вам на вход подаются число num.

Для начала, необходимо сгенерировать массив Numpy a, состоящий из num случайных чисел.

Далее необходимо сгенерировать массив b, также размерности num, но состоящий из случайных целых чисел.

Примечание: Числа должны лежать в диапазоне 1:10.

После этого необходимо создать матрицу C, которая является результатом матричного умножения a на b (т.е. результатом должна быть матрица размерности num*num).

В конце создайте массив d, который будет равен «плоской» версии матрицы C - т.е. все измерения будут приведены к 1 строке.

Важно: Постарайтесь не использовать функцию reshape для уплощения матрицы - воспользуйтесь другими методами.

Задание
Напишите функцию RandomFlatten, которая будет возвращать:

массив a
массив b
матрицу C
плоскую версию матрицы C
Функция RandomFlatten принимает на вход число num.

In [281]:
import numpy as np


class Answer:
    def RandomFlatten(self, num):
        a = np.random.randn(num)
        b = np.random.randint(1, 10, num)
        # print(a, b)
        C = np.outer(a, b)
        # print(c)
        d = C.copy().flatten()
        return a, b, C, d


print(Answer().RandomFlatten(3))

(array([1.25, 1.17, 0.73]), array([6, 7, 5]), array([[7.49, 8.73, 6.24],
       [7.01, 8.18, 5.84],
       [4.37, 5.10, 3.65]]), array([7.49, 8.73, 6.24, 7.01, 8.18, 5.84, 4.37, 5.10, 3.65]))


Numpy. ДЗ 2: Симуляция случайной выборки
Нормальная

У вас есть массив данных data, представляющих оценки студентов по некоторому предмету.

Вам необходимо написать функцию random_sample(data, k), которая будет случайным образом выбирать подмножество оценок заданного размера K из данного массива данных data.

In [282]:
def random_sample(data, k):
    return np.random.choice(data, size=k)


grades = np.array([85, 92, 78, 90, 88, 76, 95, 89, 82, 70])
print(random_sample(grades, 3))
# [92 70 90]
# не стоит ориентироваться именно на эти числа в выборке. Ведь каждый раз они будут разными

[70 70 92]


Итоговый практический кейс по numpy:

In [283]:
data = np.genfromtxt("data.csv", delimiter=",", skip_header=True)

flf = "{:.2f}".format
np.set_printoptions(formatter={"float_kind": flf})

data[:3]

array([[2016.00, 1.00, 1.00, 5.00, 0.00, 2.00, 4.00, 21.00, 2037.00,
        52.00, 0.80, 5.54, 11.65, 69.99, 1.00],
       [2016.00, 1.00, 1.00, 5.00, 0.00, 2.00, 1.00, 16.29, 1520.00,
        45.00, 1.30, 0.00, 8.00, 54.30, 1.00],
       [2016.00, 1.00, 1.00, 5.00, 0.00, 2.00, 6.00, 12.70, 1462.00,
        36.50, 1.30, 0.00, 0.00, 37.80, 2.00]])

Calc average speed

In [284]:
distances_arr = data[:, 7]
durations_arr = data[:, 8] / 3600

speed_arr = distances_arr / durations_arr
speed_arr.mean()

32.24258580925573

Amount rides in february

In [285]:
mask = data[:, 1] == 2
data[mask].shape[0]

13333

Amount rides where tips more than 50 dollars

In [286]:
data[data[:, -3] > 50].shape[0]

16

evaluate the relationship between variables

In [292]:
np.cov(data[:, [7, 8, -2]].T)

array([[26.71, 3413.20, 68.19],
       [3413.20, 10489667.24, 11345.40],
       [68.19, 11345.40, 269.92]])

In [291]:
np.corrcoef(data[:, [7, 8, -2]].T)

array([[1.00, 0.20, 0.80],
       [0.20, 1.00, 0.21],
       [0.80, 0.21, 1.00]])