In [17]:
#%pip install numpy

In [18]:
import numpy as np

: 

In [3]:
a = [1, 2, 3, 4, 5]
type(a)

list

In [4]:
an = np.array(a)
type(an)

numpy.ndarray

In [5]:
ar1 = np.array([0, 1, 2, 3])
ar2 = np.asarray([5, 6, 7, 8])

In [6]:
ar1 + ar2
ar1 * ar2
ar1 / ar2

array([0.        , 0.16666667, 0.28571429, 0.375     ])

In [10]:
ar3 = [[1,2,3], [4,5,6]]
c = np.array(ar3)

In [12]:
c.shape, c.ndim

((2, 3), 2)

In [13]:
c.sum()

21

In [14]:
c.sum(axis=0)

array([5, 7, 9])

In [15]:
c.sum(axis=1)

array([ 6, 15])